dbtype=mssql
dialect=org.hibernate.dialect.SQLServerDialect
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
jdbcurl=jdbc:sqlserver://172.17.15.102:1433;DatabaseName=@;
username=user
pwd=1fQQWoZ31Xj7qygFsMfRbVAevfqUq+Bo

#local\u5f85\u8f49\u5165\u6a94\u6848\u8def\u5f91
localPath=D:\\AM\\TF
#localPath\u5dee\u7570\u6bd4\u8f03\u6a94\u6848\u8def\u5f91
compareFolder=compare
#localPath\u932f\u8aa4\u6aa2\u6838\u6a94\u6848\u8def\u5f91
validateFolder=validate
#localPath\u56de\u88dc\u8cc7\u6599\u6a94\u6848\u8def\u5f91
revertFolder=revert
#localPath\u539f\u59cbCSV\u66ab\u5b58\u8def\u5f91
tmpFolder=originalTMP
#DB schema
schema=dbo

#\u56e0\u53f0\u9280\u6b63\u5f0f\u74b0\u5883\u4e0d\u4f7f\u7528FTP\u8f49\u6a94\u4e14IMPORT\u6307\u4ee4\u9700\u8981\u7533\u8acb\uff0c\u6545\u63a1\u7528insert,\u4ee5\u4e0b\u70ba\u66ab\u4e0d\u7528\u5340

#local\u6a94\u6848\u79fb\u81f3FTP\u4e4bsource\u8def\u5f91
sourcePath=
#\u7522\u751f\u56de\u88dc\u8cc7\u6599FTP\u4e4bsource\u8def\u5f91
sourceRevertPath=
#FTP\u9023\u7dda\u8a2d\u5b9a
ftpIP=
ftpPort=
ftpId=
ftpPwd=
#FTP / FTPS
ftpType=
ftpPath=
userId=15574

db2.username=db2inst1
db2.pwd=password